
version: '3.8'

services:
  # Development service
  frontend:
    container_name: vite-react-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn dev
    environment:
      - NODE_ENV=development
    depends_on:
      - frontend

  # Production service (NGINX)
  production:
    container_name: vite-react-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
