name: CI

on:
  push:
    branches:
      - master # adjust to your main branch name
  pull_request:
    branches:
      - master # adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Test app
        run: yarn jest


      - name: Build Application
        run: yarn build
